# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - hotfix/*

pool:
  vmImage: ubuntu-latest


variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#       - task: NuGetAuthenticate@0
- task: UseDotNet@2
  displayName: "Use .NET Core sdk"
  inputs:
    version: 5.0.x

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    arguments: "--configuration $(buildConfiguration)"

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    zipAfterPublish: false
    modifyOutputPath: false
    arguments: "--configuration $(buildConfiguration)"

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack

#- task: NuGetCommand@2
#  name: "PackMigrations"
#  inputs:
#    command: "pack"
#    packagesToPack: "gs-organisations-db.nuspec"
#    versioningScheme: "byEnvVar"
#    versionEnvVar: "PACKAGE_VERSION"
#  env:
#    PACKAGE_VERSION: $(semVer)
#- task: NuGetToolInstaller@1

